export enum CommandNamesEnum {
  gif = 'gif',
  logs = 'logs',
  reactionsAdd = 'reactions-add',
  reactionsList = 'reactions-list',
  roleAdd = 'add-role',
  roleRemove = 'remove-role',
  roleRemoveAll = 'remove-all-roles',
  role = 'role',
  roleList = 'role-list',
  schedule = 'schedule',
  shadowBan = 'shadow-ban',
  shadowBanList = 'shadow-ban-list',
  happyBirthday = 'happy-birthday',
  happyBirthday_configuration_add = 'config-add',
  happyBirthday_configuration_remove = 'config-remove',
  happyBirthday_add = 'add',
  happyBirthday_remove = 'remove',
}
